import {
  ArmchairIcon,
  ChartBarIcon,
  ChatCircleDotsIcon,
  CircleDashedIcon,
  DeviceMobileIcon,
  HeadphonesIcon,
  KeyIcon,
  MedalIcon,
  PokerChipIcon,
  ScalesIcon,
  ShieldCheckIcon,
  SparkleIcon,
  StorefrontIcon,
  TrashIcon,
  UserCircleIcon,
  CalendarCheckIcon,
  CardsIcon,
  ChartLineUpIcon,
  CoinsIcon,
  CrosshairIcon,
  CrownIcon,
  CrownSimpleIcon,
  DetectiveIcon,
  DiamondIcon,
  EyeIcon,
  FireIcon,
  FishSimpleIcon,
  HandCoinsIcon,
  HourglassIcon,
  HouseIcon,
  LightningIcon,
  PaintBrushIcon,
  RobotIcon,
  ShootingStarIcon,
  SpadeIcon,
  SquaresFourIcon,
  TrendUpIcon,
  TrophyIcon,
  UsersIcon,
  type Icon,
  type IconWeight,
} from '@phosphor-icons/react';

/** Phosphor icons referenced by name from shared/achievements.ts and src/changelog.ts. */
const ICONS: Record<string, Icon> = {
  Armchair: ArmchairIcon,
  CalendarCheck: CalendarCheckIcon,
  Cards: CardsIcon,
  ChartLineUp: ChartLineUpIcon,
  Coins: CoinsIcon,
  Crosshair: CrosshairIcon,
  Crown: CrownIcon,
  CrownSimple: CrownSimpleIcon,
  Detective: DetectiveIcon,
  Diamond: DiamondIcon,
  Eye: EyeIcon,
  Fire: FireIcon,
  FishSimple: FishSimpleIcon,
  HandCoins: HandCoinsIcon,
  Hourglass: HourglassIcon,
  House: HouseIcon,
  Lightning: LightningIcon,
  PaintBrush: PaintBrushIcon,
  Robot: RobotIcon,
  ShootingStar: ShootingStarIcon,
  Spade: SpadeIcon,
  SquaresFour: SquaresFourIcon,
  TrendUp: TrendUpIcon,
  Users: UsersIcon,
  // Changelog
  ChartBar: ChartBarIcon,
  ChatCircleDots: ChatCircleDotsIcon,
  CircleDashed: CircleDashedIcon,
  DeviceMobile: DeviceMobileIcon,
  Headphones: HeadphonesIcon,
  Key: KeyIcon,
  Medal: MedalIcon,
  PokerChip: PokerChipIcon,
  Scales: ScalesIcon,
  ShieldCheck: ShieldCheckIcon,
  Sparkle: SparkleIcon,
  Storefront: StorefrontIcon,
  Trash: TrashIcon,
  Trophy: TrophyIcon,
  UserCircle: UserCircleIcon,
};

export default function IconByName({ name, size = 20, weight = 'duotone' }: { name: string; size?: number; weight?: IconWeight }) {
  const C = ICONS[name] ?? TrophyIcon;
  return <C size={size} weight={weight} />;
}
